# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6e6bb90198bb9b598db9923a38bd692f0364b75802474fac1aa4bba1abc287bcdfdd2f4c15baf6cc1eec9bc8ae065d113546d4337055d6e4678615f900855689

test:
  secret_key_base: 15f71509f782c6fd0227a5a441fdfdc3a8305c544daff4a2f4f28017d0500bc7d11328b706fe5567d67dd3a8864848c7193634f3bddffe43aa97047c2c4831f1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
